default: &default
  adapter: postgresql
  encoding: unicode

  #Local
  port: 5432
  username: postgres
  password: postgres
  database: youtube_db_development
  host: db
  pool: 10
development:
  <<: *default
